packages:
  - "apps/*"
  - "packages/*"

overrides:
  "@types/react": "^19"
  "@types/react-dom": "^19"

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true

